### ISSUE TITLE
Update for Swift 3.0 ?

### ISSUE THREAD

**Issue by fadylateef** [PayalUmraliya/PUGifLoaderControl#1]
When used with XCode 9.0 and Swift 4.0 , it shows error at import line 

`Module compiled with Swift 3.0.2 cannot be imported in Swift 3.2.3`

**Comment by Mamtak1811** [comment]
Any solution to this? I am trying to use it in Swift 3.1. But still getting the same issue

**Comment by pratikjoshi74** [comment]
i still getting same issue any solution?

**Comment by Mamtak1811** [comment]
No Solution found. You can use MBProgressHUD third party library for gifs
too.

**Comment by PayalUmraliya** [comment]
Please go through this pod

https://github.com/PayalUmraliya/PUGifLoading
